# Generated by Django 4.2.4 on 2023-11-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='course_type',
        ),
    ]
