# Generated by Django 4.2.4 on 2023-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_dish_ingredients_remove_dish_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_video_url',
        ),
        migrations.AddField(
            model_name='instructions',
            name='instruction_video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
