# Generated by Django 4.2.4 on 2023-11-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_dish_dish_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='customizable_ingredients',
        ),
    ]
